### ISSUE TITLE
`heroku docker:release` doesn't detect changes in local code, only Dockerfile

### ISSUE THREAD

**Issue by freeformz** [heroku/heroku-container-tools#75]
And because of this the docker is not instructed to build the image again and the existing image only get's re-released.

**Comment by nilnullzip** [comment]
1. Same problem here. heroku docker:release appears to be deploying the last version deployed instead of rebuilding based on the revised code.

2. "docker build" (non heroku) works fine to detect the code change and rebuild. But no way to get heroku to deploy that version.

3. One workaround is to clear out the heroku images:

    heroku docker:clean
    heroku docker:release

But then you lose your heroku image history.

Have others encountered this issue? Seems like a big gotcha that would be noticed by many. Perhaps there is some configurations in which it occurs and others where it does not?

**Comment by hunterloftis** [comment]
I suspect the compose branch will resolve this, as it instructs `docker-compose` to build before each release:

- https://github.com/heroku/heroku-docker/blob/a497da6ad2ded2c43542bf060ee1b6c95cdca856/commands/release.js#L98

**Comment by azylman** [comment]
Is there any timeline for the compose branch? Or some way I can install it into my heroku toolbelt?
