### ISSUE TITLE
What is the relationship with buildpacks?

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-container-tools#78]
Initially, one of our stated goals was to avoid buildpacks and to see what a Docker workflow could be like "fresh." Is this still a path we want to pursue?

Pros: Buildpacks are mature, stable, and well-understood (internally).

Cons: Buildpacks are difficult to compose, unweildy (node -> bash, ruby -> huge), and poorly understood (externally)

**Comment by hunterloftis** [comment]
If we rely on buildpacks to do it now, and then put that code into the docker registry, I think it's exceedingly unlikely we will change it later. Thoughts @friism @hone @dzuelke ?

**Comment by ojacobson** [comment]
One big limitation of the buildpack system as implemented is that _every buildpack step requires a project to operate on_. The `detect` script inspects the project, so must run with a project. The `compile` script both reads the project files to build things and uses the project directory to store additional components (language runtimes, eg.. The `release` script inspects the built project.

This completely cripples Docker's image-layering techniques: anything Docker-based that uses buildpacks will either need to cheat (by violating the buildpack API) or will need to re-install every additional component a buildpack requires on every change to the project, because the project layer happens before the buildpack evaluation, so changes to the project tree will invalidate previously-cached buildpack steps.

I think we collectively understand that already, but I haven't seen it written down in too many places. :)

Now - I don't think cheating with the buildpack API is necessarily a bad thing. I think we're nearing the limits of the kinds of systems we can compose out of buildpacks, and bending the API is a great way to explore how we might change or replace the buildpack API to better support other kinds of app. I agree with @hunterloftis that if we weakly commit to buildpacks as they are, we'll likely discover that we've made a strong commitment and be unable to revisit that decision for a long time. This is a new API for our customers, and launching it under the Heroku banner implies a Heroku-ish level of support for it.

**Comment by cyx** [comment]
I think the feeling of limitation mostly comes from the lack of apt-get or
any suitable package management. Working around those things and doing the
/app hack ties is down considerably.

**Comment by cyx** [comment]
Playing devil's advocate and not wanting buildpacks -- means we need to make an image for ruby that supports all the combinations of versions for jvm / node

_or_

we make a base image, and figure out a good way to layer JVM / node combinations from there.

Until that problem is tightly / neatly solved can we at least try to imagine a world without buildpacks.

**Comment by friism** [comment]
Do we really have to support all those combinations? I checked the current JRuby implementation on Heroku and, while it's possible to get different JVM with `java.runtime.version`, it's not a documented part of JRuby support.

I think it's fine if we support the versions of JRuby that users want, running on the default JVM and node version. If some user needs a different JVM or Node for some esoteric, they can grab our Dockerfile and modify it.

The problem of more sophisticated layering is interesting, but I doubt it's a big problem for most users running apps on default configs.

**Comment by cyx** [comment]
I guess the ruby peeps can speak to that more -- seeing they have the
largest buildpack that I know of. I'm all for simplicity as well (but not
if it makes 50% of the population an outcast).

If it's the case that only 5% or less use it, let's do it `FROM ruby:2.2.2`
style and see where it takes us?

**Comment by friism** [comment]
+1

**Comment by hunterloftis** [comment]
https://github.com/heroku/heroku-docker/tree/compose leaves buildpack choice to platform implementers. The initial platform test (node) doesn't use a buildpack.
