### ISSUE TITLE
docker:init creates invalid Dockerfile if node version has wildcard(s)

### ISSUE THREAD

**Issue by dotnetCarpenter** [heroku/heroku-container-tools#91]
While this:
```json
"engines": {
  "node": "0.12.x"
}
```
is valid in package.json, it is does not work when [`curl` a node release in the Dockerfile](https://github.com/heroku/heroku-docker/blob/master/platforms/node/Dockerfile.t#L13).

The issue is that `heroku docker:init` reads the node property and inserts it directly in the `Dockerfile`.

Example:
```
ENV NODE_ENGINE 0.12.x
ENV PORT 3001

RUN mkdir -p /app/heroku/node
RUN mkdir -p /app/src
RUN curl -s https://s3pository.heroku.com/node/v$NODE_ENGINE/node-v$NODE_ENGINE-linux-x64.tar.gz | tar --strip-components=1 -xz -C /app/heroku/node
```

[Line 13](https://github.com/heroku/heroku-docker/blob/master/platforms/node/Dockerfile.t#L13) should be written differently by `heroku docker:init` to support [the same version information as npm](https://docs.npmjs.com/files/package.json#engines).

**Comment by hunterloftis** [comment]
Hi @dotnetCarpenter, this is expected behavior - initially, we're avoiding semver resolution for engines to keep complexity down. We may ultimately end up adopting wildcards again, but they actually create a lot of problems (accidental engine upgrades and mismatches between local and prod binaries).

Another consideration is that the next version of heroku-docker will pull down explicit images from the docker hub, eg "heroku/node:0.12.3" - in which case wildcards will also be impossible since the docker hub doesn't resolve semver ranges in tags (afaik).

**Comment by dotnetCarpenter** [comment]
Right. I hear what you're saying. A better solution could be to print out a warning, so users (like me) don't need to hunt down the source of the *bug*.

**Comment by dotnetCarpenter** [comment]
`RUN echo $NODE_ENGINE | grep -vq ^[0-9\.]*$ && echo "Wrong node version" `
should print "Wrong node version" if the version is not an absolute version. Not sure how you cancel a docker process though.

**Comment by joeyespo** [comment]
Ran into this. It would indeed be helpful to have a message instead of tracking this down manually. Using semver in `engines` is quite common, and what's shown in [the docs](https://docs.npmjs.com/files/package.json#engines).
